## ANIKET PATIL
### Github :- https://github.com/aniketpatil91/ImdbSentimentAnalysis

## CNN

In [10]:
%matplotlib inline
import itertools
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding, SpatialDropout1D
from keras.layers import LSTM
from keras.layers import Conv1D, GlobalMaxPooling1D ,MaxPooling1D
from keras.layers import Flatten
from keras.datasets import imdb
from keras.utils import plot_model
from keras.utils.vis_utils import model_to_dot

In [2]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=5000)
x_train = sequence.pad_sequences(x_train, maxlen=400)
x_test = sequence.pad_sequences(x_test, maxlen=400)

In [3]:
model = Sequential()
model.add(Embedding(5000, 50,  input_length=400))
model.add(Dropout(0.2))
model.add(Conv1D(250, 3,padding='valid',activation='relu',strides=1))
model.add(GlobalMaxPooling1D())
model.add(Dense(250))
model.add(Dropout(0.2))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 400, 50)           250000    
_________________________________________________________________
dropout_1 (Dropout)          (None, 400, 50)           0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 398, 250)          37750     
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 250)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 250)               62750     
_________________________________________________________________
dropout_2 (Dropout)          (None, 250)               0         
_________________________________________________________________
activation_1 (Activation)    (None, 250)               0         
__________

In [4]:
model.fit(x_train, y_train, batch_size=64,epochs=4,validation_data=(x_test, y_test),verbose=1)

Train on 25000 samples, validate on 25000 samples
Epoch 1/4
25000/25000 [==============================] - 205s 8ms/step - loss: 0.4408 - acc: 0.7720 - val_loss: 0.2916 - val_acc: 0.8774
Epoch 2/4
25000/25000 [==============================] - 199s 8ms/step - loss: 0.2428 - acc: 0.9016 - val_loss: 0.2575 - val_acc: 0.8940
Epoch 3/4
25000/25000 [==============================] - 218s 9ms/step - loss: 0.1703 - acc: 0.9338 - val_loss: 0.2732 - val_acc: 0.8892
Epoch 4/4
25000/25000 [==============================] - 223s 9ms/step - loss: 0.1158 - acc: 0.9592 - val_loss: 0.3001 - val_acc: 0.8854


In [5]:
score, acc = model.evaluate(x_test, y_test, batch_size=64)
preds = model.predict_classes(x_test, batch_size=64)

25000/25000 [==============================] - 27s 1ms/step


In [6]:
cm = confusion_matrix(y_test, preds)
print(cm)

[[11451  1049]
 [ 1817 10683]]


In [7]:
print(classification_report(y_test,preds))

             precision    recall  f1-score   support

          0       0.86      0.92      0.89     12500
          1       0.91      0.85      0.88     12500

avg / total       0.89      0.89      0.89     25000



## RCNN

In [8]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=5000)
x_train = sequence.pad_sequences(x_train, maxlen=400)
x_test = sequence.pad_sequences(x_test, maxlen=400)

In [11]:
model = Sequential()
model.add(Embedding(5000,  50,input_length=400))
model.add(Dropout(0.25))
model.add(Conv1D(64,5,padding='valid',activation='relu',strides=1))
model.add(MaxPooling1D(pool_size=4))
model.add(LSTM(70))
model.add(Dense(1))
model.add(Activation('sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 400, 50)           250000    
_________________________________________________________________
dropout_4 (Dropout)          (None, 400, 50)           0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 396, 64)           16064     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 99, 64)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 70)                37800     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 71        
_________________________________________________________________
activation_3 (Activation)    (None, 1)                 0         
Total para

In [12]:
model.fit(x_train, y_train,batch_size=64,epochs=4,validation_data=(x_test, y_test),verbose=1)

Train on 25000 samples, validate on 25000 samples
Epoch 1/4
25000/25000 [==============================] - 103s 4ms/step - loss: 0.4028 - acc: 0.8003 - val_loss: 0.2793 - val_acc: 0.8857
Epoch 2/4
25000/25000 [==============================] - 112s 4ms/step - loss: 0.2297 - acc: 0.9098 - val_loss: 0.2714 - val_acc: 0.8873
Epoch 3/4
25000/25000 [==============================] - 114s 5ms/step - loss: 0.1801 - acc: 0.9326 - val_loss: 0.2774 - val_acc: 0.8847
Epoch 4/4
25000/25000 [==============================] - 110s 4ms/step - loss: 0.1487 - acc: 0.9455 - val_loss: 0.2980 - val_acc: 0.8816


In [13]:
score, acc = model.evaluate(x_test, y_test, batch_size=64)
preds = model.predict_classes(x_test, batch_size=64)

25000/25000 [==============================] - 26s 1ms/step


In [14]:
cm = confusion_matrix(y_test, preds)
print(cm)

[[10525  1975]
 [  986 11514]]


In [15]:
print(classification_report(y_test,preds))

             precision    recall  f1-score   support

          0       0.91      0.84      0.88     12500
          1       0.85      0.92      0.89     12500

avg / total       0.88      0.88      0.88     25000



## LSTM

In [16]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=20000)

In [17]:
x_train = sequence.pad_sequences(x_train, maxlen=80)
x_test = sequence.pad_sequences(x_test, maxlen=80)

In [18]:
model = Sequential()
model.add(Embedding(20000, 128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 128)         2560000   
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 129       
Total params: 2,691,713
Trainable params: 2,691,713
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(x_train, y_train, batch_size=32,epochs=4,validation_data=(x_test, y_test))

Train on 25000 samples, validate on 25000 samples
Epoch 1/4
25000/25000 [==============================] - 135s 5ms/step - loss: 0.4615 - acc: 0.7806 - val_loss: 0.4067 - val_acc: 0.8165
Epoch 2/4
25000/25000 [==============================] - 148s 6ms/step - loss: 0.3015 - acc: 0.8748 - val_loss: 0.3749 - val_acc: 0.8355
Epoch 3/4
25000/25000 [==============================] - 135s 5ms/step - loss: 0.2205 - acc: 0.9136 - val_loss: 0.4285 - val_acc: 0.8311
Epoch 4/4
25000/25000 [==============================] - 143s 6ms/step - loss: 0.1526 - acc: 0.9433 - val_loss: 0.4487 - val_acc: 0.8245


In [20]:
score, acc = model.evaluate(x_test, y_test, batch_size=32)
preds = model.predict_classes(x_test, batch_size=32)

25000/25000 [==============================] - 20s 802us/step


In [21]:
cm = confusion_matrix(y_test, preds)
print(cm)

[[10672  1828]
 [ 2560  9940]]


In [22]:
print(classification_report(y_test,preds))

             precision    recall  f1-score   support

          0       0.81      0.85      0.83     12500
          1       0.84      0.80      0.82     12500

avg / total       0.83      0.82      0.82     25000

